apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git' # 본인 리포지토리 주소
    targetRevision: HEAD
    path: base/metallb # (1)에서 저장한 MetalLB 매니페스트 경로
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # 네임스페이스가 없으면 자동으로 생성