apiVersion: v1
kind: ConfigMap
metadata:
  name: es-s3-settings # ConfigMap의 이름
  namespace: efkstack
data:
  # 이 내용이 elasticsearch.yml 파일에 추가될 설정이 됩니다.
  elasticsearch.yml: |
    s3.client.default.access_key: ${aws_access_key}
    s3.client.default.secret_key: ${aws_secret_key}