apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- elastalert-deployment.yaml

configMapGenerator:
- name: elastalert-config
  options:
    disableNameSuffixHash: true
  files:
  - config.yaml
  - service_error_rule.yaml
  - system_auth_fail_rule.yaml
  - system_kmsg_error_rule.yaml