server.publicBaseUrl: "http://172.20.10.4:5601"
xpack.security.authc.providers:
  anonymous:
    anonymous1:
      order: 100
      credentials:
        username: "anonymous_user"
        roles: ["anonymous_dashboard_reader"]
xpack.security.sameSiteCookies: None