apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kibana.yaml

configMapGenerator:
- name: kibana-extra-config
  options:
    disableNameSuffixHash: true
  namespace: efkstack
  files:
  - kibana.yml=kibana-config.yaml 